### ISSUE TITLE
Currently block and fileshare functions are split in the sushi.

### ISSUE THREAD

**Issue by jackhaibo** [opensds/opensds#939]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
The switch between the block and fileshare functions in the current sushi needs to modify the `opensdsstoragetype` parameter to block or file in the `csi-configmap-opensdsplugin.yaml` file and then use command `kubectl replace -f .` to restart the csi pods, then function can run normally. This implementation is equivalent to two plugins.
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: csi-configmap-opensdsplugin
data:
  opensdsendpoint: http://8.46.187.238:50040
  opensdsauthstrategy: noauth
  opensdsstoragetype: block
  osauthurl: http://127.0.0.1/identity
  osusername: admin
  ospassword: opensds@123
  ostenantname: admin
  osprojectname: admin
  osuserdomainid: default
  passwordencrypter: aes
  enableEncrypted: F
  osuserdomainid: default
```

**What you expected to happen**:
According to @xing-yang, the fileshare and block are in the same plugin.

**Anything else we need to know?**:
In fact, the main reason that the two functions of block and fileshare cannot be placed in the same plugin is that during the deletion process, csi can only obtain the `volumeId `parameter and cannot obtain other parameters to judge whether the current deletion is volume or fileshare.

**Environment**:
- Sushi(release/branch) version: latest
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
